language: node_js
node_js:
- stable
script:
  - sls create -t spotinst-nodejs -p ../test
  - npm link && cd ../test && npm link serverless-spotinst-functions
  - npm i serverless -s
  - serverless config credentials -p spotinst -t ${token} -a ${account}